# Generated by Django 3.1.2 on 2020-10-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='created_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
