# Generated by Django 3.1.2 on 2020-11-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201102_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.PositiveIntegerField(default=100000),
        ),
    ]
